matrix:
  fast_finish: true     # immediately finish build once one of the jobs fails.

environment:
  matrix:
    - PYTHON_VERSION: "3.6"
      MINICONDA: C:\Miniconda36-x64

build: false

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set show_channel_urls true --set changeps1 no
  - conda update -q conda
  - conda update --all
  - conda config --add channels conda-forge
  - conda config --set channel_priority strict
  - conda env create -f environment.yml

test_script:
  - activate earth-analytics-python
  - conda list
  - python -c "import rasterio"
  #- python -c "import earthpy"
