name: earth-analytics-python
channels:
  - conda-forge
dependencies:
  # Core scientific python
  - openssl
  - matplotlib
  - python>=3.6
  - tornado=5.1.1
  - pyqt
  - seaborn
  - tqdm

  # Spatial libraries
  - rasterstats
  - geopy
  - cartopy
  - geopandas
  - rasterio
  - contextily
  - pysal
  - pyproj
  - folium
  - gdal
  - libgdal
  - kealib
  - geocoder
  - geojson

  # Natural language processing
  - tweepy
  - nltk
  - textblob

  # Jupyter Environment
  - autopep8
  - notebook
  - ipython
  - jupyter_contrib_nbextensions
  - jupyterlab
  - nb_conda

  - pip:
      # Utilities
      - download
      - nbclean
      # EA tools via pip
      - mapboxgl
      - hydrofunctions
      - git+https://github.com/earthlab/earthpy.git@cdfb644eba02b2ab43d8ce16baa76f4ea478cfcd
