name: earth-analytics-python
channels:
  - conda-forge
dependencies:
  # Core scientific python
  - numpy
  - matplotlib
  - python=3.6
  - pyqt
  - seaborn

  # Geo stuff
  - rasterstats
  - geopy
  - cartopy
  - geopandas
  - rasterio
  - contextily
  - pysal
  - pyproj
  - folium
  - scikit-image
  - gdal
  - geocoder
  - geojson
  
  # natural language processing
  - tweepy
  - nltk 

  # Jupyter Environment
  - notebook
  - ipython
  - jupyter_contrib_nbextensions
  - jupyterlab
  - nb_conda


  - pip:
      # Utilities
      - download
      - nbgrader
      - nbclean
      - mne
      - sklearn
      - tqdm
      - kiwisolver
      - mapboxgl
      - git+https://github.com/geopandas/geopandas.git
      - git+https://github.com/earthlab/earthpy.git@283683affac9e46b1690c7913ebd2621c82ba43a
