name: earth-analytics-python
channels:
  - nodefaults
  - conda-forge
dependencies:
  # Core scientific python
  - numpy
  - matplotlib
  - python=3.6
  - pyqt
  - seaborn
  - tqdm
  - kiwisolver
  - scipy

  # Extensions
  - autopep8

  # Geo stuff
  - rasterstats
  - geopy
  - cartopy
  - geopandas
  - rasterio
  - contextily
  - pysal
  - pyproj
  - folium
  - scikit-image
  - gdal
  - libgdal
  - kealib
  - geocoder
  - geojson

  # Natural language processing
  - tweepy
  - nltk
  - textblob

  # Jupyter Environment
  - notebook
  - ipython
  - jupyter_contrib_nbextensions
  - jupyterlab
  - nb_conda
  - nbgrader

  - pip:
      # Utilities
      - download
      - nbclean
      # EA tools via pip
      - mapboxgl
      - hydrofunctions
      - earthpy
